// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehBNMd61asD9-kmK8PmGhpuXBsROdlBI',
    appId: '1:297062741181:web:9cab06f8338411ee14b3d4',
    messagingSenderId: '297062741181',
    projectId: 'riverpod-firestore-strea-76823',
    authDomain: 'riverpod-firestore-strea-76823.firebaseapp.com',
    storageBucket: 'riverpod-firestore-strea-76823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC126c2FeHtW73HHrIRRMau9MX9fVQyro',
    appId: '1:297062741181:android:2d157df75d83e26714b3d4',
    messagingSenderId: '297062741181',
    projectId: 'riverpod-firestore-strea-76823',
    storageBucket: 'riverpod-firestore-strea-76823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDem9Fr-YPtDvE41uecydj_2e9XwMeyKSU',
    appId: '1:297062741181:ios:3fecc75655d98b7214b3d4',
    messagingSenderId: '297062741181',
    projectId: 'riverpod-firestore-strea-76823',
    storageBucket: 'riverpod-firestore-strea-76823.appspot.com',
    iosClientId: '297062741181-v6s23qlpnuiku9k8vdrhtijptipfrkn0.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
