// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENzcQQKhN_rLtd8iaQHn-K9Bf8Oaz3IU',
    appId: '1:427757070:web:7c373871e12b5bf23cf65f',
    messagingSenderId: '427757070',
    projectId: 'riverpod-firestore-strea-52399',
    authDomain: 'riverpod-firestore-strea-52399.firebaseapp.com',
    storageBucket: 'riverpod-firestore-strea-52399.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMI22lgjSlJLfszGm8gkWb2pjqgXxIGmM',
    appId: '1:427757070:android:bf987cc54f9fe8003cf65f',
    messagingSenderId: '427757070',
    projectId: 'riverpod-firestore-strea-52399',
    storageBucket: 'riverpod-firestore-strea-52399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzx1ryknNkZTp59AEPOs31_9hNMnaEE8',
    appId: '1:427757070:ios:087a2bb8f5e4eef13cf65f',
    messagingSenderId: '427757070',
    projectId: 'riverpod-firestore-strea-52399',
    storageBucket: 'riverpod-firestore-strea-52399.appspot.com',
    iosClientId: '427757070-ggn8fbp4gvdri785coonbtvsc915eh5t.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
